name: Upload to S3
on:
  push:
    branches:
      - INTERN-770 
  pull_request:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  
  AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }} 
  AWS_DEFAULT_REGION: ${{ secrets.TF_VAR_REGION }}

jobs:
  create-resources:
    runs-on: ubuntu-latest
        
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
            
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Run Terraform commands
        env:
          TF_VAR_bucket: ${{ secrets.TF_VAR_BUCKET }}
          TF_VAR_key: ${{ secrets.TF_VAR_KEY }}
          TF_VAR_region: ${{ secrets.TF_VAR_REGION }}
        run: |
          cd terraform
          terraform init
          terraform plan -var-file="var.tfvars"
          terraform apply -var-file="var.tfvars" -auto-approve

  upload-to-s3:
    runs-on: ubuntu-latest
    needs: create-resources
        
    steps:
      - name: Checkout code 
        uses: actions/checkout@v3

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt install -y awscli  
        
      - name: Add ansible files to S3
        run: aws s3 cp ansible/ s3://sneha-tf-test-bucket/ --recursive

